### ISSUE TITLE
Translation to Pt_BR

### ISSUE THREAD

**Issue by Ramys** [alexkulya/pandaria_5.4.8#6]
Even modifying internally, the missions and conversation continue in Spanish.
is there any Db in pt_BR?

**Comment by alexkulya** [comment]
@Ramys 
This happens because some tasks, objects, creatures have the wrong standard language (English) and are not tied to any language locale. I do not plan to add a translation to other languages, if you have the opportunity and desire, you can do it yourself and make a request to add to this repository.

**Comment by Ramys** [comment]
I will work on it soon.
